# Treaty Education - Website / Repository
# Developer: Jericho Crosby (built for Sharon Annett)
# Copyright (c) 2026 Sharon Annett (Treaty Education). All rights reserved.
# This repository and its contents are proprietary to Sharon Annett (Treaty Education).
# Use, copying, modification, distribution, or derivation without permission is strictly prohibited.

title: Treaty Education
description: Treaty Education - Sharon Annett
baseurl: ""
url: "https://treatyeducation.co.nz"
incremental: true